// Mocks generated by Mockito 5.0.16 from annotations
// in oldwave/test/src/use_case/detail_product_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:oldwave/src/models/detail_product.dart' as _i2;
import 'package:oldwave/src/models/repository/detail_product_repository.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDetailProduct_0 extends _i1.Fake implements _i2.DetailProduct {}

/// A class which mocks [DetailProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetailProductRepository extends _i1.Mock
    implements _i3.DetailProductRepository {
  MockDetailProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DetailProduct> getDetailProductById(
          int? idProduct, int? idSeller) =>
      (super.noSuchMethod(
              Invocation.method(#getDetailProductById, [idProduct, idSeller]),
              returnValue:
                  Future<_i2.DetailProduct>.value(_FakeDetailProduct_0()))
          as _i4.Future<_i2.DetailProduct>);
  @override
  String toString() => super.toString();
}
